version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    # run tests1
    docker:
      - image: cimg/python:3.8-node
    working_directory: ~/project/app
    steps:
      - checkout
      - run:
          name: Install pylint
          command: pip install pylint  
      - run:
          name: Run pylint
          command: pylint --output-format=parseable --disable=E401 --fail-under=5 app/app.py app/wsgi.py app/modules/backend.py

  build_docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image 
          command: |
            docker login registry.gitlab.com -u opsdev45 -p $GITLAB_TOKEN
            docker build -t registry.gitlab.com/opsdev45/container:1.$CIRCLE_BUILD_NUM .
            docker push registry.gitlab.com/opsdev45/container:1.$CIRCLE_BUILD_NUM
      - run:
          name: send message to discord
          command: > 
            curl -X POST -H "Content-Type: application/json" -d '{"content": "New Docker image pushed: registry.gitlab.com/opsdev45/container:1.'"${CIRCLE_BUILD_NUM}"'"}' $DISCORD_WEBHOOK_URL

      # - run:
      #     name: Run container  
      #     command: |
      #       docker run -p 8000:8000 -d registry.gitlab.com/opsdev45/container:1.$CIRCLE_BUILD_NUM 
      # - run:
      #     name: Test container  
      #     command: |
      #       pip install requests pytest
      #       python test.py
  


workflows:
  build-and-test:
    jobs:
      - test-python
      #- build_docker:
       #   requires:
        #    - test-python
