version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    # run tests1
    docker:
      - image: cimg/python:3.8-node
    working_directory: ~/project/app
    steps:
      - checkout
      - run:
          name: Install pylint
          command: pip install pylint
      - run:
          name: Run pylint
          command: pylint --output-format=parseable --disable=E401 --fail-under=5 app/app.py app/wsgi.py app/modules/backend.py

  build_docker:
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          environment:
            DOCKER_USER: devops45of
            DOCKER_PASS: ${{ secrets.DOCKER_PASSWD }}
          command: |
            docker login -u "$DOCKER_USER" -p Qwerasdf132 
            docker build -t devops45of/app:1.$CIRCLE_BUILD_NUM .
            docker push devops45of/app:1.$CIRCLE_BUILD_NUM

workflows:
  build-and-test:
    jobs:
      - test-python
      - build_docker:
          requires:
            - test-python
