name: dev pipeline
on: 

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Build Docker image
      run: docker build -t devops45of/app:test -t devops45of/app:${{ github.sha }} .
    
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: devops45of
        password: ${{ secrets.DOCKER_PASSWD }}
    
    
    - name: Push Docker image to DockerHub
      run: docker push devops45of/app --all-tags
    - name: Trigger deployment pipeline in another repository
      run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            https://api.github.com/repos/opsdev45/argocd/dispatches \
            -d '{"event_type": "trigger_deployment", "client_payload": {"sha": "${{ github.sha }}"}}'

    

      
    
